import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
import './globals.css'
import {ClerkProvider} from "@clerk/nextjs";

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
})


export const metadata: Metadata = {
  title: 'MathQuiz',
  description: 'Generated by create next app',
  icons: {
      icon: '/assets/icons/logo.svg'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <ClerkProvider>
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
      </ClerkProvider>
  )
}
